==15942== Memcheck, a memory error detector
==15942== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==15942== Using Valgrind-3.24.0 and LibVEX; rerun with -h for copyright info
==15942== Command: python3 -m pytest
==15942== Parent PID: 2764
==15942== 
==15942== Invalid write of size 1
==15942==    at 0x949D5BC: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x94313d8 is 24 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D5D5: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x94313c0 is 0 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid write of size 8
==15942==    at 0x949D5F0: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x94313c0 is 0 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D60E: UnknownInlinedFun (object.h:361)
==15942==    by 0x949D60E: UnknownInlinedFun (object.h:944)
==15942==    by 0x949D60E: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x9430e70 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D61F: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D61F: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x9430e70 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid write of size 8
==15942==    at 0x949D62A: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D62A: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x9430e70 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D631: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D631: genwrapper_next (genwrapper.c:323)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x9430e70 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid write of size 1
==15942==    at 0x949D5BC: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x7cda008 is 24 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D5D5: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x7cd9ff0 is 0 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid write of size 8
==15942==    at 0x949D5F0: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x7cd9ff0 is 0 bytes inside a block of size 32 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x949A7B8: callback_dealloc (awaitable.c:21)
==15942==    by 0x949A15B: call_deallocator_maybe (array.c:8)
==15942==    by 0x949A5A6: pyawaitable_array_clear_items (array.c:142)
==15942==    by 0x949AA88: pyawaitable_cancel_impl (awaitable.c:126)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x949AB64: pyawaitable_await_impl (awaitable.c:145)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D60E: UnknownInlinedFun (object.h:361)
==15942==    by 0x949D60E: UnknownInlinedFun (object.h:944)
==15942==    by 0x949D60E: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x63d48c0 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D61F: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D61F: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x63d48c0 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid write of size 8
==15942==    at 0x949D62A: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D62A: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x63d48c0 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Invalid read of size 8
==15942==    at 0x949D631: UnknownInlinedFun (object.h:948)
==15942==    by 0x949D631: genwrapper_next (genwrapper.c:323)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Address 0x63d48c0 is 16 bytes inside a block of size 192 free'd
==15942==    at 0x48478EF: free (vg_replace_malloc.c:989)
==15942==    by 0x49878E1: UnknownInlinedFun (object.h:949)
==15942==    by 0x49878E1: coro_wrapper_dealloc (genobject.c:1223)
==15942==    by 0x949AB2F: UnknownInlinedFun (object.h:949)
==15942==    by 0x949AB2F: pyawaitable_cancel_impl (awaitable.c:131)
==15942==    by 0x94D3595: ffi_call_unix64 (unix64.S:104)
==15942==    by 0x94D000D: ffi_call_int.lto_priv.0 (ffi64.c:673)
==15942==    by 0x94D2BD2: ffi_call (ffi64.c:710)
==15942==    by 0x8ABEE4B: UnknownInlinedFun (callproc.c:950)
==15942==    by 0x8ABEE4B: _ctypes_callproc (callproc.c:1300)
==15942==    by 0x8ABCE0D: PyCFuncPtr_call (_ctypes.c:4386)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x8ABA960: _CallPythonObject (callbacks.c:226)
==15942==    by 0x8ABAB2F: closure_fcn (callbacks.c:310)
==15942==    by 0x94D3151: ffi_closure_unix64_inner (ffi64.c:899)
==15942==    by 0x94D37B7: ffi_closure_unix64 (unix64.S:303)
==15942==    by 0x949CEB5: genwrapper_next (genwrapper.c:284)
==15942==    by 0x949C402: genwrapper_next (genwrapper.c:209)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Block was alloc'd at
==15942==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==15942==    by 0x49D7BC1: UnknownInlinedFun (obmalloc.c:1302)
==15942==    by 0x49D7BC1: UnknownInlinedFun (pycore_object_alloc.h:46)
==15942==    by 0x49D7BC1: UnknownInlinedFun (gc.c:1848)
==15942==    by 0x49D7BC1: _PyObject_GC_NewVar (gc.c:1887)
==15942==    by 0x4AE509B: make_gen (genobject.c:873)
==15942==    by 0x4A584EF: _Py_MakeCoro (genobject.c:914)
==15942==    by 0x4A0467D: _PyEval_EvalFrameDefault (generated_cases.c.h:5220)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942== 
==15942== Conditional jump or move depends on uninitialised value(s)
==15942==    at 0x949CF97: genwrapper_next (genwrapper.c:288)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Uninitialised value was created by a stack allocation
==15942==    at 0x7081010: ???
==15942== 
==15942== Conditional jump or move depends on uninitialised value(s)
==15942==    at 0x949D1B2: genwrapper_next (genwrapper.c:297)
==15942==    by 0x4A05021: _PyEval_EvalFrameDefault (generated_cases.c.h:5314)
==15942==    by 0x4AE569C: UnknownInlinedFun (pycore_ceval.h:119)
==15942==    by 0x4AE569C: gen_send_ex2 (genobject.c:229)
==15942==    by 0x8AA07AD: task_step_impl (_asynciomodule.c:2782)
==15942==    by 0x8AA1E87: task_step (_asynciomodule.c:3101)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x49A21F4: context_run (context.c:664)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x4ADCB35: _PyObject_Call (call.c:361)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:373)
==15942==    by 0x4A061B3: UnknownInlinedFun (call.c:381)
==15942==    by 0x4A061B3: _PyEval_EvalFrameDefault (generated_cases.c.h:1355)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACDD92: _PyObject_VectorcallDictTstate (call.c:146)
==15942==    by 0x4B24B41: UnknownInlinedFun (call.c:504)
==15942==    by 0x4B24B41: slot_tp_call (typeobject.c:9533)
==15942==    by 0x49EC02B: _PyObject_MakeTpCall (call.c:242)
==15942==    by 0x4A0B42F: _PyEval_EvalFrameDefault (generated_cases.c.h:1502)
==15942==    by 0x4ACFCE4: PyEval_EvalCode (ceval.c:601)
==15942==    by 0x4AE9443: UnknownInlinedFun (bltinmodule.c:1145)
==15942==    by 0x4AE9443: builtin_exec (bltinmodule.c.h:556)
==15942==    by 0x4A1B55C: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:441)
==15942==    by 0x49EFA1C: UnknownInlinedFun (pycore_call.h:168)
==15942==    by 0x49EFA1C: PyObject_Vectorcall (call.c:327)
==15942==    by 0x4A04BEA: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==15942==    by 0x4B0902E: pymain_run_module (main.c:349)
==15942==    by 0x4B04544: UnknownInlinedFun (main.c:690)
==15942==    by 0x4B04544: Py_RunMain (main.c:775)
==15942==    by 0x4ABF57B: Py_BytesMain (main.c:829)
==15942==    by 0x4E48E07: (below main) (libc_start_call_main.h:58)
==15942==  Uninitialised value was created by a stack allocation
==15942==    at 0x7081010: ???
==15942== 
==15942== 
==15942== HEAP SUMMARY:
==15942==     in use at exit: 3,040,470 bytes in 33,630 blocks
==15942==   total heap usage: 749,739 allocs, 716,109 frees, 112,114,054 bytes allocated
==15942== 
==15942== LEAK SUMMARY:
==15942==    definitely lost: 1,186,712 bytes in 20,763 blocks
==15942==    indirectly lost: 45 bytes in 1 blocks
==15942==      possibly lost: 1,157,133 bytes in 9,593 blocks
==15942==    still reachable: 696,580 bytes in 3,273 blocks
==15942==         suppressed: 0 bytes in 0 blocks
==15942== Rerun with --leak-check=full to see details of leaked memory
==15942== 
==15942== For lists of detected and suppressed errors, rerun with: -s
==15942== ERROR SUMMARY: 19 errors from 16 contexts (suppressed: 0 from 0)
